title: Ben B's Portfolio
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Ben Bretton # add your name
author-img: senior-pic.jpg # add your photo
about-author: I am the electrical subteam lead for FRC team 2363 Triple Helix. # add description
twitter: # add your Twitter handle
facebook: ben.bretton # add your Facebook handle
github: wbenb # add your Github handle
linkedin: # add your Linkedin handle
email: wbbretton@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
